This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file C:/Users/pat/Desktop/Vorlage-Masterarbeit/Masterarbeit.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Masterarbeit.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file Masterarbeit.acr....done (6 lines written, 0 warnings).
Output written in Masterarbeit.acr.
Transcript written in Masterarbeit.alg.
